version: '3'

services:
  web:
    image: test-google-python:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /srv/application_default_credentials.json
      GCLOUD_PROJECT: testing-python-415909
    volumes:
      - ./src:/srv/www:delegated
      - $HOME/.config/gcloud/application_default_credentials.json:/srv/application_default_credentials.json
    healthcheck:
      disable: true
